name: deploy to lambda

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Find and Replace API TOKEN - Using Build Variable
      run: find gramet/*.py -type f -exec sed -i ''s/{GOATCOUNTER}/${{ secrets.GOATCOUNTER }}/g'' {} \;
    - name: deploy app.py
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: gramet
        source: gramet/app.py
